return {
  'akinsho/bufferline.nvim',
  dependencies = {
    'moll/vim-bbye',
		'nvim-tree/nvim-web-devicons',
  },
  config = function()
    require('bufferline').setup {
      options = {
        mode = 'buffers',
        numbers = 'none',
        close_command = 'Bdelete! %d',
        right_mouse_command = 'Bdelete! %d',
        left_mouse_command = 'buffer %d',
        middle_mouse_command = nil,
        buffer_close_icon = '✗',
        close_icon = '✗',
        path_components = 1,
        modified_icon = '●',
        left_trunc_marker = '',
        right_trunc_marker = '',
        max_name_length = 50,
        max_prefix_length = 50,
        tab_size = 25,
        diagnostics = false,
        color_icons = false,
        show_buffer_icons = false,
        show_buffer_close_icons = true,
        show_close_icon = false,
        persist_buffer_sort = true,
        separator_style = { '│', '│' },
        enforce_regular_tabs = true,
        always_show_bufferline = true,
        show_tab_indicators = false,
        indicator = { style = 'none' },
        icon_pinned = '󰐃',
        minimum_padding = 0,
        maximum_padding = 0,
        maximum_length = 0,
        sort_by = 'insert_at_end',
      },
    }
  end,
}
