bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/tmux/plugins"
# Plugins
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
# TPM plugin manager
run '~/.config/tmux/tmux/plugins/tpm/tpm'

#-- GENERAL SETTINGS
set -g default-terminal "tmux-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g mouse off
set -g status-right-length 0
set -g status-left-length 0
set -g status-style ""
set -g pane-border-status top

#-- TMUX SETTINGS 
set -g status-left " #[fg=#00ffff]#(~/.config/tmux/tmux/scripts/tmux_activity.sh)#[default] "

set -g status-right "🗗 :#S:#I.#P  #[bold]⌛#[nobold]#(~/.config/tmux/tmux/scripts/tmux_uptime.sh)  #[bold]💻#[nobold] #(hostname)  #[bold]🖧#[nobold]  #(~/.config/tmux/tmux/scripts/tmux_ip.sh)  🖴  #(~/.config/tmux/tmux/scripts/tmux_disk.sh)  #{tmux_mode_indicator}"
set -g window-status-format " #I #W "
set -g window-status-current-format "[#I #W]"
set -g pane-border-format "#{?pane_active,#[fg=#5294e2]>>> ACTIVE <<<, }"
set -g pane-border-style "fg=colour255"
set -g pane-active-border-style "fg=colour255"

#-- Prefix
set -g prefix `                     # prefix key
bind ` send-prefix                  # send prefix

#-- Remove defaults
unbind C-b                          # remove C-b
unbind %                            # remove %
unbind '"'                          # remove "

#-- Sessions
bind-key M-[ switch-client -p       # alt+[  prev session
bind-key M-] switch-client -n       # alt+]  next session
bind-key M-\; new-session           # alt+;  new session

#-- Split panes
bind "M-\\" split-window -h         # alt+\  split left/right
bind "M-'"  split-window -v         # alt+'  split up/down
bind S setw synchronize-panes       # S sync panes

#-- Windows (no prefix)
bind -n S-Down  new-window          # shift+down  new win
bind -n S-Left  previous-window     # shift+left  prev win
bind -n S-Right next-window         # shift+right next win

#-- Move between panes
bind -n C-M-Left  select-pane -L    # ctrl+alt+left  pane left
bind -n C-M-Right select-pane -R    # ctrl+alt+right pane right
bind -n C-M-Up    select-pane -U    # ctrl+alt+up    pane up
bind -n C-M-Down  select-pane -D    # ctrl+alt+down  pane down

#-- Move windows
bind -n M-H swap-window -t -1       # alt+shift+h  move win left
bind -n M-L swap-window -t +1       # alt+shift+l  move win right





